import React from 'react';

interface RIAAdviceProps {
  advice: { advice: string; query_used: string; status: string } | null;
  onGetAdvice: () => Promise<void>;
  isLoading: boolean;
}

const RIAAdvice: React.FC<RIAAdviceProps> = ({ advice, onGetAdvice, isLoading }) => {
  const handleGetAdvice = async () => {
    await onGetAdvice();
  };

  const formatAdvice = (text: string) => {
    // Convert markdown-style formatting to HTML-like structure for rendering
    return text.split('\n').map((line, index) => {
      if (line.startsWith('**') && line.endsWith('**')) {
        return (
          <h4 key={index} className="text-lg font-semibold text-white mt-4 mb-2">
            {line.replace(/\*\*/g, '')}
          </h4>
        );
      } else if (line.startsWith('-')) {
        return (
          <li key={index} className="text-gray-300 ml-4 mb-1">
            {line.replace('-', '').trim()}
          </li>
        );
      } else if (line.match(/^\d+\./)) {
        return (
          <li key={index} className="text-gray-300 ml-4 mb-2 list-decimal">
            {line.replace(/^\d+\.\s*/, '')}
          </li>
        );
      } else if (line.trim() === '') {
        return <br key={index} />;
      } else {
        return (
          <p key={index} className="text-gray-300 mb-2">
            {line}
          </p>
        );
      }
    });
  };

  return (
    <div className="bg-gray-900 rounded-lg p-6 border border-gray-800">
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-xl font-bold text-white flex items-center">
          <span className="text-2xl mr-2">🧠</span>
          RIA Investment Advice
        </h3>
        <button
          onClick={handleGetAdvice}
          disabled={isLoading}
          className="px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 text-white rounded-lg transition-colors duration-200 flex items-center"
        >
          {isLoading ? (
            <>
              <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Analyzing...
            </>
          ) : (
            <>
              <span className="mr-2">📊</span>
              Get RIA Advice
            </>
          )}
        </button>
      </div>

      {advice ? (
        <div className="space-y-4">
          {advice.status === 'no_api_key' ? (
            <div className="bg-yellow-900 border border-yellow-700 rounded-lg p-4">
              <div className="flex items-center">
                <span className="text-2xl mr-3">⚠️</span>
                <div>
                  <h4 className="text-yellow-400 font-semibold">API Key Required</h4>
                  <p className="text-yellow-200 text-sm">
                    Please add your Groq API key to the .env file to get RIA advice.
                  </p>
                </div>
              </div>
            </div>
          ) : advice.status === 'error' ? (
            <div className="bg-red-900 border border-red-700 rounded-lg p-4">
              <div className="flex items-center">
                <span className="text-2xl mr-3">❌</span>
                <div>
                  <h4 className="text-red-400 font-semibold">Error</h4>
                  <p className="text-red-200 text-sm">
                    {advice.advice}
                  </p>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-gray-800 rounded-lg p-6 border border-gray-700">
              <div className="flex items-center mb-4">
                <span className="text-3xl mr-3">👨‍💼</span>
                <div>
                  <h4 className="text-lg font-semibold text-white">Certified Financial Planner Analysis</h4>
                  <p className="text-gray-400 text-sm">Professional investment advice based on your portfolio and risk profile</p>
                </div>
              </div>
              
              <div className="prose prose-invert max-w-none">
                {formatAdvice(advice.advice)}
              </div>

              <div className="mt-6 pt-4 border-t border-gray-700">
                <div className="flex items-center text-sm text-gray-400">
                  <span className="mr-2">💡</span>
                  <span>This advice is generated by AI and should be considered along with professional financial guidance.</span>
                </div>
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="text-center py-8">
          <div className="text-6xl mb-4">🧠</div>
          <h4 className="text-lg font-semibold text-white mb-2">RIA Investment Analysis</h4>
          <p className="text-gray-400 mb-4">
            Get personalized investment advice based on your portfolio allocation and risk tolerance
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-left">
            <div className="bg-gray-800 rounded-lg p-4 border border-gray-700">
              <div className="flex items-center mb-2">
                <span className="text-xl mr-2">📊</span>
                <h5 className="text-white font-medium">Portfolio Analysis</h5>
              </div>
              <p className="text-gray-400 text-sm">
                Review your current investment allocation and performance
              </p>
            </div>
            <div className="bg-gray-800 rounded-lg p-4 border border-gray-700">
              <div className="flex items-center mb-2">
                <span className="text-xl mr-2">⚖️</span>
                <h5 className="text-white font-medium">50/30/20 Strategy</h5>
              </div>
              <p className="text-gray-400 text-sm">
                Get recommendations based on proven asset allocation principles
              </p>
            </div>
            <div className="bg-gray-800 rounded-lg p-4 border border-gray-700">
              <div className="flex items-center mb-2">
                <span className="text-xl mr-2">🎯</span>
                <h5 className="text-white font-medium">Risk-Adjusted</h5>
              </div>
              <p className="text-gray-400 text-sm">
                Advice tailored to your personal risk tolerance
              </p>
            </div>
          </div>
        </div>
      )}

      {/* SQL Trace */}
      {advice && (
        <div className="mt-6 p-3 bg-gray-800 rounded border border-gray-700">
          <p className="text-xs text-gray-400 font-mono">
            Query: {advice.query_used}
          </p>
        </div>
      )}
    </div>
  );
};

export default RIAAdvice;
